#!/bin/bash
sudo apt install hping3
# equired essentials for Hydra
sudo apt-get -y install build-essential
sudo apt-get install git
sudo apt-get install hydra
sudo apt-get install tcpdump
sudo apt-get install python3
sudo apt install python3-pip
pip install --pre scapy[basic]
pip install scapy
sudo python3 main.py